spring:
  application:
    name: todo-app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 290903
    url: "jdbc:mysql://localhost:3306/todoapp"
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
